# !important
unstable_features = true

# No neat way of sorting these options... 
max_width = 80
merge_derives = false
group_imports = "StdExternalCrate"
fn_single_line = true
binop_separator = "Back"
imports_granularity = "Item"
use_small_heuristics = "Max"
force_multiline_blocks = false
overflow_delimited_expr = true
use_field_init_shorthand = true
