unstable_features = true

# use_small_heuristics = "Max"
max_width = 120

group_imports = "StdExternalCrate"
imports_granularity = "Module"

use_field_init_shorthand = true
overflow_delimited_expr = true

merge_derives = false
