# !important
unstable_features = true

# No neat way of sorting these options... 
max_width = 80
brace_style = "PreferSameLine"
wrap_comments = true
merge_derives = false
group_imports = "StdExternalCrate"
fn_single_line = true
binop_separator = "Back"
trailing_semicolon = false
imports_granularity = "Item"
use_small_heuristics = "Max"
force_multiline_blocks = false
overflow_delimited_expr = true
use_field_init_shorthand = true
match_block_trailing_comma = true
format_code_in_doc_comments = true
