unstable_features = true

# Sorting
group_imports = "StdExternalCrate"
# imports_granularity = "Module"
imports_granularity = "Item"
merge_derives = false

# Size
use_small_heuristics = "Max"
max_width = 80
fn_single_line = true
use_field_init_shorthand = true
overflow_delimited_expr = true
force_multiline_blocks = false
