[package]
name = "haskfmt"
description = "Formats JSON files like Haskell records."
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.215"
serde_json = { version = "1.0.133", features = ["preserve_order"] }
thiserror = "2.0.3"
