[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
glium = "0.36.0"
strum = "0.26.2"
thiserror = "2.0.3"
winit = "0.30.5"
