[package]
name = "sdfc"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[dependencies]
anyhow = "1.0.98"
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_bytes = "0.11.17"
serde_json = "1.0.140"
thiserror = "2.0.12"
toml = "0.8.22"
